//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Bankalar.Module.BusinessObjects.dbDeneme2
{

    [Persistent(@"oz_gecmis")]
    public partial class OzGecmis : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fad_soyad;
        [Size(50)]
        public string ad_soyad
        {
            get { return fad_soyad; }
            set { SetPropertyValue<string>(nameof(ad_soyad), ref fad_soyad, value); }
        }
        decimal ftelefon;
        public decimal telefon
        {
            get { return ftelefon; }
            set { SetPropertyValue<decimal>(nameof(telefon), ref ftelefon, value); }
        }
        string fadres;
        [Size(50)]
        public string adres
        {
            get { return fadres; }
            set { SetPropertyValue<string>(nameof(adres), ref fadres, value); }
        }
        string fhobiler;
        [Size(50)]
        public string hobiler
        {
            get { return fhobiler; }
            set { SetPropertyValue<string>(nameof(hobiler), ref fhobiler, value); }
        }
        string fdeneyimler;
        [Size(50)]
        public string deneyimler
        {
            get { return fdeneyimler; }
            set { SetPropertyValue<string>(nameof(deneyimler), ref fdeneyimler, value); }
        }

        private System.Drawing.Image image;

        [ValueConverter(typeof(ImageValueConverter))]
        public System.Drawing.Image Image
        {
            get { return image; }
            set
            {
                SetPropertyValue(nameof(Image), ref image, value);
            }
        }


        // private System.Drawing.Image image2;
        //[ValueConverter(typeof(ImageValueConverter))]
        //public System.Drawing.Image Image2
        //{
        //    get { return image2; }
        //    set
        //    {
        //        SetPropertyValue(nameof(Image2), ref image2, value);
        //    }
        //}


        //System.Drawing.Image picture;
        //[ValueConverter(typeof(ImageValueConverter)), Stream("StreamPicture", "image/jpeg")]
        //public System.Drawing.Image Picture
        //{
        //    get { return picture; }
        //    set
        //    {
        //        SetPropertyValue("Picture", ref picture, value);
        //    }
        //}
    }

}
