//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;

namespace Bankalar.Module.BusinessObjects.dbDeneme2
{

    [Persistent(@"tbl_subeler")]
    public partial class Subeler : XPLiteObject
    {
        Guid fid;
        [Key(true)]
        [ColumnDbDefaultValue("(newid())")]
        public Guid id
        {
            get { return fid; }
            set { SetPropertyValue<Guid>(nameof(id), ref fid, value); }
        }
        Guid fbanka_id;
        [VisibleInDetailView(false)]
        [VisibleInListView(false)]
        public Guid banka_id
        {
            get { return fbanka_id; }
            set { SetPropertyValue<Guid>(nameof(banka_id), ref fbanka_id, value); }
        }
        string fsubeAdi;
        [Size(50)]
        public string subeAdi
        {
            get { return fsubeAdi; }
            set { SetPropertyValue<string>(nameof(subeAdi), ref fsubeAdi, value); }
        }


        [Association]
        public XPCollection<Bankalar> Bankalars
        {
            get { return GetCollection<Bankalar>(nameof(Bankalars)); }
        }


        [Association]
        public XPCollection<tbl_hesaplar> Hesaplars
        {
            get { return GetCollection<tbl_hesaplar>(nameof(Hesaplars)); }
        }



        //private Bankalar bankalar;
        //[Association("Bankalar-Subeler")]
        //public Bankalar Bankalars
        //{
        //    get { return bankalar; }
        //    set { SetPropertyValue(nameof(Bankalar), ref bankalar, value); }
        //}


        //[Association]
        //public XPCollection<Subeler> Subelers
        //{
        //    get { return GetCollection<Subeler>(nameof(Subelers)); }
        //}

    }

}
